# fly.toml app configuration file generated for hys-surl-project-11 on 2024-11-06T15:21:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hys-surl-project-11'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
SPRING_PROFILES_ACTIVE = "prod,secret"