server:
  port: 8080
  address: 0.0.0.0
  shutdown: graceful
spring:
  autoconfigure:
    exclude:
  lifecycle:
    timeout-per-shutdown-phase: 1h
  datasource:
        url: jdbc:mysql://172.17.0.2:3306/surl_prod
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 172.17.0.1
      port: 6379
      password: ${custom.secret.spring.data.redis.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    com.hys.exam.surl_project_11: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    name: "My Site Prod"